### ISSUE TITLE
Рефакторинг метода InitPathToLog

### ISSUE THREAD

**Issue by vadim-ruzh** [vadim-ruzh/Logger#13]
Пришлось приложить усилие чтобы понять зачем нужны эти строчки. Код должен быть понятным и следовать принципу наименьшего удивления. Чтобы улучшить можно написать комментарий, либо вынести в отдельную функцию.

_Originally posted by @reficul0 in https://github.com/vadim-ruzh/Logger/pull/9#discussion_r837019549_

**Comment by reficul0** [comment]
Готово
